name: snowflake-demo
name: app_environment
channels:
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - snowflake
  - nodefaults
dependencies:
dependencies:
  - python=3.9
  - python=3.9.*
  - pip
  - snowbooks=1.32.0
  - openssl=1.1.1
  - streamlit=1.26.0
  - pip:
    # Snowflake
    - snowflake-cli-labs
    - snowflake-snowpark-python
    - snowflake
